title: slvjoe's learning to blog on Github
author: slvJoe
email: email@josefrosie.co.uk
description: > # this means to ignore newlines until "baseurl:"
  This isn't an awesome description for my new site here. I will try to make more of an effort.
Although, I'm only using this to learn with
# social links
twitter_username: @slvjoe
github_username:  slvjoe

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
